name:                KWIC
version:             0.1.0.0
github:              "githubuser/KWIC"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/KWIC#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- safe

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src  # Ajustado para o diretório correto da biblioteca (src)

executables:
  KWIC-exe:
    main:                Main.hs
    source-dirs:         app  # Diretório correto para o executável
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KWIC
    - containers
    - safe

tests:
  KWIC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KWIC
    - hspec
    - safe
